# Generated by Django 3.2.9 on 2021-11-19 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('company_url', models.CharField(max_length=250, verbose_name='Компания')),
                ('location', models.CharField(max_length=150, verbose_name='Локация')),
                ('income', models.CharField(max_length=150, verbose_name='Доход')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150, verbose_name='Полное имя')),
                ('job_title', models.CharField(max_length=150, verbose_name='Посада')),
                ('profile_url', models.CharField(max_length=250, verbose_name='Профиль')),
                ('location', models.CharField(max_length=250, verbose_name='Локация')),
                ('email', models.EmailField(max_length=254, verbose_name='Эл. адрес')),
                ('phone_number', models.CharField(max_length=254, verbose_name='Номер телефона')),
            ],
        ),
    ]
